# SPRING
spring:
  # MAIN
  main:
    banner-mode: off

  # APPLICATION
  application:
    name: SimpleUser

  # DATABASE
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  # JPA
  jpa:
    # HIBERNATE
    hibernate:
      ddl-auto: update # TODO: include liquibase
    # PROPERTIES
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true

  # H2
  h2:
    # CONSOLE
    console:
      enabled: true
      path: /h2

  # SECURITY
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

# JWT
jwt:
  key: ${JWT_KEY}
  expiration: ${JWT_EXPIRATION_MS}